### ISSUE TITLE
please store logs in their own directory - preferably use tempdir to allow moodle to clean up/remove

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_yookassa#71]
it would be better to put your log files in moodle's "tempdir" rather than the root of the dataroot:
https://github.com/Snickser/moodle-paygw_yookassa/blob/main/callback.php#L92

do a search on moodle code for "make_temp_directory" or $CFG->tempdir to see how it's used in other places.

**Comment by Snickser** [comment]
I removed this code.
