### ISSUE TITLE
anonymous users can flag any existing invoice as cancelled.

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_yookassa#73]
https://github.com/Snickser/moodle-paygw_yookassa/blob/main/callback.php#L44

This means that anyone can cancel any payment (even previously paid ones?) and update the cancellation reason with any text they want - there should definitely be some better validation there.

**Comment by Snickser** [comment]
I tried to implement it, but I forgot and now it seems it will never be in demand.
