### ISSUE TITLE
unrestricted file upload

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_yookassa#75]
When savedebugdata is on, the callback.php allows anyone to post data to the script and the full data is saved into a file on the server. 

You could mitigate this by making it a lot clearer on the setting description that leaving savedebugdata should not be left on when the plugin is running on a production environment.

One example of this being a problem would be someone filling up the dataroot with large files, potentially taking down your site because the disk is full.

This doc describes some of the other issues:
https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload

**Comment by Snickser** [comment]
Yes, I did it for myself during development, but now it is not really needed for production systems. I removed this code.
